### PR TITLE
Add Step Time Digits Testing

### LINKED ISSUE #42: Review and Add to Front End Testing
Tests need to be checked for correctness/clarity and more tests can be added to protect the main branch on the frontend.

**Acceptance Criteria**

- [x] Review front-end tests and edit for correctness (add comments if helpful)
- [x] Add more front-end tests to protect the main branch

### PR DESCRIPTION
**Pull request by colinseper**
Fixes #42 

What was changed:
- Added testing to check that previous functionality for representing Step Time Values in was properly visualized and the data was correctly represented.

Why it was changed:
- Testing was added to ensure the prior functionality worked as intended and to create a fail-safe for future changes that could break the intended functionality.

How it was changed:
- Updated StepTimeDigits view, adding id's to make it easier for testing.
- Created StepTimeDIgits test file, adding tests to ensure the structure was correctly represented and the data was properly represented.

### CODE REVIEW

**Comment by colinseper** [comment]
I cancelled the backend test workflow because there are currently bugs.

**Comment by JackMcPhillips1543** [comment]
The tests look good and pass, I'll approve once my PR merges

**Review by git-voo — CHANGES_REQUESTED** [review]
This is a great job Collin. Everything looks good. Just reconcile this with the Lint fixes on Jack's branch to get the pipeline checks passing and we're good to go.

**Review by JackMcPhillips1543 — APPROVED** [review]

**Review by git-voo — APPROVED** [review]
Great job Collin!
Let's get this in.

**Pull request merged**
