### PR TITLE
Add StepTimeTreadmill View

### LINKED ISSUE #27: Create Additional View for Step Time Depiction
**Objective**
Design a view for displaying step time values in a format similar to the example picture given by Dr. Jason. 

A picture of the image and a description are below:

image

In this case the X's would be the right and left step time target zones and the sets of bar's are the current left and right step time.

_Note: We may want to follow up with Dr. Jason first to ensure his idea for a visual hasn't changed since our lab visit._

**Acceptance Criteria**
- [x] Follow up about ideal step time visualization with Dr. Jason
- [ ] Implement new visualization as a view
- [x] Add the view to the navbar component so it can be swapped similarly to the other views
- [x] Add tests to ensure the component and swapping work properly:
     - [x] The user can see the new visualization as a view on the screen
     - [x] The new view can be properly swapped to using the navbar
- [x]  Ensure when running `npm test` in the frontend directory all prior and current tests pass

### PR DESCRIPTION
**Pull request by colinseper**
Fixes #27 

_Note: This PR is not finalized due to a pending response from the client based on the wants and needs for the visualization being implemented. Therefore there are some changes to the code that will likely need to be updated regardless of functionality (at the minimum) based on client response. Additionally UI changes will be made when the client responds so there isn't a constant need for shifting until the client functionality needs are met._

What was changed:

- Added display for a stepTimeTreadmill visualization. 
- Added functionality to allow swapping to the new visualization.
- Added testing to ensure swapping to the new visualization worked and it is properly displayed.

Why it was changed:

- The visualization was added to have another way to relay the step time data in accordance with the client.
- The functionality was added for visualization swapping so the webpage could properly be accessed.
- The testing was added to ensure the new visualization was properly displayed and to protect the main branch.

How it was changed:

- Created StepTimeTreadmill.js and StepTimeTreadmill.css to create the visualization and style it.
- Updated Naviagtion.js to handle swapping between the new view.
- Updated App.test.js to ensure the new view could be swapped to and was properly rendered.

### CODE REVIEW

**Comment by JackMcPhillips1543** [comment]
Is the target parameter supposed to be the force data and the zones? When I open and run this the graph is extremely condensed.
Screenshot 2024-11-11 at 6 14 46 PM
I think the range of things need to be fixed

**Review by git-voo — DISMISSED** [review]
Nicely done! this will be a good placeholder until we figure out how the view should look exactly

**Comment by colinseper** [comment]
> Is the target parameter supposed to be the force data and the zones? When I open and run this the graph is extremely condensed. Screenshot 2024-11-11 at 6 14 46 PM I think the range of things need to be fixed

Do you know what the target zones were? If you have target zones == to the step time target values then this will happen, but I may need to adjust for the max position each can be.

**Comment by colinseper** [comment]
If it is run it will look like 2 orange lines at the top of the screen. This is because all values for step_time, target zone etc. are set to 0.

**Review by JackMcPhillips1543 — APPROVED** [review]
Geat job fixing up the view it looks good to go!

**Review by git-voo — APPROVED** [review]

**Pull request merged**
